2434Tools/Controllers/LiverController.cs
using _2434Tools.Data;
using _2434Tools.Models;
using _2434Tools.Models.ViewModels;
using _2434Tools.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Google.Apis.Services;
using Google.Apis.YouTube.v3;

namespace _2434Tools.Controllers
{
    public class LiverController : Controller
    {
        #region Declarations
        readonly ApplicationDbContext _context;
        readonly IUserPermissionsService _permissions;
        public LiverController(ApplicationDbContext context, IUserPermissionsService permissions)
        {
            this._context = context;
            this._permissions = permissions;
        }
        #endregion
        #region Index
        public async Task<IActionResult> Index(Int32? id)
        {
            if (id != null) return this.RedirectToAction("Details", new { id });
            var GroupLivers = await _context.Groups.Include(_group => _group.Livers).ToListAsync();
            ViewBag.GroupLivers = GroupLivers;
            return this.View();
        }
        // Details
        public async Task<IActionResult> Details(Int32 id)
        {
            // Bad await usage
            var Liver   = await _context.Livers.SingleOrDefaultAsync(_liver => _liver.Id == id);
            if (Liver == null) return this.NotFound();
            // Will take videos ordered by publish date. 
            // Perhaps we should separate live and upcoming from the rest
            var Videos = await _context.Videos.Where(_video => _video.LiverId == id)
                                            .OrderByDescending(_video => _video.Published)
                                            .Take(20).ToListAsync();
            ViewBag.Liver = Liver;
            ViewBag.Videos = Videos;
            return this.View("Details");
        }
        #endregion
        #region Create
        public async Task<IActionResult> Create()
        {
            if (!_permissions.IsAdmin()) return this.NotFound();
            ViewBag.Groups = new SelectList(await _context.Groups.ToListAsync(), "Id", "Name");
            return this.View(new LiverViewModel() { Graduated = false });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LiverViewModel model)
        {
            if (!_permissions.IsAdmin()) return this.NotFound();
            if (ModelState.IsValid)
            {
                var Liver = new Liver()
                {
                    ChannelId = model.ChannelId,
                    Name = model.Name,
                    Graduated = model.Graduated,
                    GroupId = model.GroupId,
                    TwitterLink = model.TwitterLink
                };
                if (await AddLiverInfo(Liver))
                {
                    _context.Add(Liver);
                    await _context.SaveChangesAsync();
                    return this.RedirectToAction("Index");
                } else
                {
                    ModelState.AddModelError("ChannelId", "Make sure channel's Id is correct!");
                }
            }
            ViewBag.Groups = new SelectList(await _context.Groups.ToListAsync(), "Id", "Name", model.GroupId);
            return this.View(model);
        }
        #endregion
        #region Edit
        public async Task<IActionResult> Edit(Int32 id)
        {
            if (!_permissions.IsAdmin()) return this.NotFound();
            var Liver = await _context.Livers.SingleOrDefaultAsync(_liver => _liver.Id == id);
            if (Liver == null) return this.NotFound();
            var Groups = await _context.Groups.ToListAsync();
            ViewBag.Groups = new SelectList(Groups, "Id", "Name", Groups.Where(_group => _group.Id == Liver.GroupId));
            return this.View(new LiverViewModel()
            { Graduated = Liver.Graduated, GroupId = Liver.GroupId, Name = Liver.Name, TwitterLink = Liver.TwitterLink, ChannelId = Liver.ChannelId });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Int32 id, LiverViewModel model)
        {
            if (!_permissions.IsAdmin()) return this.NotFound();
            var Liver = await _context.Livers.SingleOrDefaultAsync(_liver => _liver.Id == id);
            if (Liver == null) return this.NotFound();
            if (ModelState.IsValid)
            {
                Liver.GroupId = model.GroupId;
                Liver.Name = model.Name;
                Liver.Graduated = model.Graduated;
                Liver.TwitterLink = model.TwitterLink;
                await _context.SaveChangesAsync();
                return this.RedirectToAction("Index");
            }
            ViewBag.Groups = new SelectList(await _context.Groups.ToListAsync(), "Id", "Name", model.GroupId);
            return this.View(model);
        }
        #endregion
        #region Delete
        public async Task<IActionResult> Delete(Int32 id)
        {
            if (!_permissions.IsAdmin()) return this.NotFound();
            var Liver = await _context.Livers.SingleOrDefaultAsync(_liver => _liver.Id == id);
            if (Liver == null) return this.NotFound();
            ViewBag.Liver = Liver;
            return this.View();
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteSingle(Int32 id)
        {
            if (!_permissions.IsAdmin()) return this.NotFound();
            var Liver = await _context.Livers.SingleOrDefaultAsync(_liver => _liver.Id == id);
            if (Liver == null) return this.NotFound();
            _context.Remove(Liver);
            await _context.SaveChangesAsync();
            return this.RedirectToAction("Index");
        }
        #endregion
        #region Helpers
        private async Task<Boolean> AddLiverInfo(Liver liver)
        {
            var youtubeService = new YouTubeService(new BaseClientService.Initializer()
            {
                ApiKey = Variables.API_KEY,
                ApplicationName = this.GetType().ToString()
            });
            var channel_request = youtubeService.Channels.List("snippet,statistics,brandingSettings");
            channel_request.Id = liver.ChannelId;
            try
            {
                var response = (await channel_request.ExecuteAsync()).Items[0];
                liver.ChannelName = response.Snippet.Title;
                liver.Description = response.Snippet.Description;
                liver.Subscribers = (uint)response.Statistics.SubscriberCount;
                liver.Views = (ulong)response.Statistics.ViewCount;
                if (response.Snippet.Thumbnails.Standard != null)
                {
                    liver.PictureURL = response.Snippet.Thumbnails.Standard.Url;
                }
                else if (response.Snippet.Thumbnails.High != null)
                {
                    liver.PictureURL = response.Snippet.Thumbnails.High.Url;
                }
                else if (response.Snippet.Thumbnails.Medium != null)
                {
                    liver.PictureURL = response.Snippet.Thumbnails.Medium.Url;
                }
                else if (response.Snippet.Thumbnails.Default__ != null)
                {
                    liver.PictureURL = response.Snippet.Thumbnails.Default__.Url;
                }
                liver.ThumbURL = response.Snippet.Thumbnails.Default__.Url;
                if (response.BrandingSettings.Image?.BannerExternalUrl != null)
                {
                    liver.BannerURL = response.BrandingSettings.Image.BannerExternalUrl;
                }
            } catch(NullReferenceException)
            {
                return false;
            }
            return true;
        }
        #endregion
    }
}

2434Tools/Views/Shared/_BaseLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _2434Tools</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom-site-max.css" />
</head>
<body>
    <nav class="navbar d-flex flex-row position-absolute box-shadow" style="right:0;">
        <div class="d-sm-inline-flex flex-row">
            <ul class="navbar-nav flex-grow-1 flex-row">
                <li class="nav-item">
                    <div>
                        <img style="width: 2rem; height: 2rem" src="~/icons/live-streaming.svg" />
                        <a class="nav-link text-dark stretched-link" asp-area="" asp-controller="Home" asp-action="Index">Live</a>
                    </div>
                </li>
                <li class="nav-item">
                    <div>
                        <img style="width: 1.8rem; height: 1.8rem; margin: 0.1rem 0" src="~/icons/subscription.svg" />  
                        <a class="nav-link text-dark stretched-link" asp-area="" asp-controller="Liver" asp-action="Index">Channels</a>
                    </div>
                </li>
                @if (User.IsInRole(_2434Tools.Data.ApplicationRoles.Administrators))
                {
                    <li class="nav-item">
                        <div>
                            <div style="width: 2rem; height: 2rem" id="groupsBackground"></div>
                            <a class="nav-link text-dark stretched-link" asp-area="" asp-controller="Group" asp-action="Index">Groups</a>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <style>
        #groupsBackground {
            background: url("/icons/holoen-hug.jpg");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            filter: grayscale();
        }
        .navbar {
            padding: 0;
            border-radius: 4rem 0 0 4rem;
            padding: .125rem 0;
        }
        .nav-item > * {
            display: flex;
            flex-direction: column;
            align-items: center;
            position: relative;
            padding: .125rem;
            width: 100%;
            height: 100%;
            justify-content: flex-end;
        }
        .nav-item:first-of-type:hover {
            border-radius: 4rem 0 0 4rem;
        }
        .nav-item a {
            font-size: 0.85rem;
        }
        .nav-item {
            width: 5.7rem;
            height: 5rem;
            display: flex;
        }
        .nav-item:hover {
            background: rgba(74, 74, 74, 0.3);
        }

        @@media screen and (max-width: 767px) {
            .nav-item {
                width: 100%;
            }

            .nav-item > * {
                flex-direction: row;
                padding: .4rem .8rem;
            }

            .nav-item a {
                font-size: 0;
            }
        }
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

2434Tools/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _2434Tools</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom-site-max.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 p-sm-0 p-2">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">2434Tools</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <div>
                                <img style="width: 2rem; height: 2rem" src="~/icons/live-streaming.svg"/>
                                <a class="nav-link text-dark stretched-link" asp-area="" asp-controller="Home" asp-action="Index">Live</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div>
                                <img style="width: 1.8rem; height: 1.8rem; margin: 0.1rem 0" src="~/icons/subscription.svg" />
                                <a class="nav-link text-dark stretched-link" asp-area="" asp-controller="Liver" asp-action="Index">Channels</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div>
                                <img style="width: 2rem; height: 2rem" src="~/icons/multiview.svg" />
                                <a class="nav-link text-dark stretched-link" href="/Multiview">MultiView</a>
                            </div>
                        </li>
                        @if (User.IsInRole(_2434Tools.Data.ApplicationRoles.Administrators))
                        {
                            <li class="nav-item">
                                <div>
                                    <div style="width: 2rem; height: 2rem" id="groupsBackground"></div>
                                    <a class="nav-link text-dark stretched-link" asp-area="" asp-controller="Group" asp-action="Index">Groups</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <form id="formSignOut" asp-controller="Account" asp-action="Logout" method="post">
                                    <img style="width: 2rem; height: 2rem" src="~/icons/exit.svg" />
                                    <button id="signOut" type="submit" class="nav-link btn btn-link text-dark stretched-link" tabindex="-1">Sign out</button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>  
    <style>
        #groupsBackground {
            background: url("/icons/holoen-hug.jpg");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            filter: grayscale();
        }
        .navbar {
            padding: 0.6rem 1.2rem !important;
        }
        .nav-item > * {
            display: flex;
            flex-direction: column;
            align-items: center;
            position: relative;
            padding: .4rem .4rem 0;
            justify-content: space-between;
        }
        .nav-item a, .nav-item button {
            font-size: 0.85rem;
        }
        .nav-link {
            padding-bottom: 0;
        }
        .nav-item {
            width: 5.7rem;
            height: 4.2rem;
        }
        .nav-item:hover {
            background: rgba(74, 74, 74, 0.2);
        }
        @@media screen and (max-width: 575px) {
            .nav-item:first-of-type {
                margin-top: 0.5rem;
            }
            .nav-item {
                width: 100%;
                display: flex;
                align-items: center;    
            }
            .nav-item > * {
                width: 100%;
                flex-direction: row;
                padding: .4rem .8rem;
            }
            .nav-link {
                padding: 0;
            }
            .nav-item a, .nav-item button {
                font-size: 1.2rem;
            }
        }
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>